CREATE DATABASE HOSPITAL;
USE HOSPITAL;

CREATE TABLE CLINICA_MEDICA (
    ID_NRO_UNIDADE INT NOT NULL AUTO_INCREMENT,
    NOME_UNIDADE VARCHAR(90) NOT NULL,
    CNPJ VARCHAR(18) NOT NULL,
    EMAIL VARCHAR(70) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_NRO_UNIDADE)
);

CREATE TABLE PACIENTE (
    ID_PACIENTE INT NOT NULL AUTO_INCREMENT,
    ID_NRO_UNIDADE INT NOT NULL,
    NOME_PACIENTE VARCHAR(70) NOT NULL,
    DT_NSC DATE NOT NULL,
    SEXO VARCHAR(20) NOT NULL,
    ESTADO_CIVIL VARCHAR(40) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_PACIENTE),
    FOREIGN KEY (ID_NRO_UNIDADE) REFERENCES CLINICA_MEDICA(ID_NRO_UNIDADE)
);

CREATE TABLE MEDICO (
    NRO_MEDICO INT NOT NULL AUTO_INCREMENT,
    ID_NRO_UNIDADE INT NOT NULL,
    NOME_MEDICO VARCHAR(70) NOT NULL,
    DT_NSC DATE NOT NULL,
    SEXO VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    PRIMARY KEY (NRO_MEDICO),
    FOREIGN KEY (ID_NRO_UNIDADE) REFERENCES CLINICA_MEDICA(ID_NRO_UNIDADE)
);

CREATE TABLE CONSULTA (
    NRO_CONSULTA INT NOT NULL AUTO_INCREMENT,
    NRO_MEDICO INT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    PRIMARY KEY (NRO_CONSULTA),
    FOREIGN KEY (NRO_MEDICO) REFERENCES MEDICO(NRO_MEDICO),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);

CREATE TABLE EXAME (
    ID_EXAME INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    OBS TEXT,
    PRIMARY KEY (ID_EXAME)
);

CREATE TABLE CONSULTA_EXAME (
    NRO_CONSULTA INT NOT NULL,
    ID_EXAME INT NOT NULL,
    OBS TEXT,
    PRIMARY KEY (NRO_CONSULTA, ID_EXAME),
    FOREIGN KEY (NRO_CONSULTA) REFERENCES CONSULTA(NRO_CONSULTA),
    FOREIGN KEY (ID_EXAME) REFERENCES EXAME(ID_EXAME)
);

CREATE TABLE CONVENIO (
    ID_CONVENIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_CONVENIO)
);

CREATE TABLE CLINICA_CONVENIO (
    ID_NRO_UNIDADE INT NOT NULL,
    ID_CONVENIO INT NOT NULL,
    PRIMARY KEY (ID_NRO_UNIDADE, ID_CONVENIO),
    FOREIGN KEY (ID_NRO_UNIDADE) REFERENCES CLINICA_MEDICA(ID_NRO_UNIDADE),
    FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO(ID_CONVENIO)
);

CREATE TABLE PACIENTE_CONVENIO (
    ID_PACIENTE INT NOT NULL,
    ID_CONVENIO INT NOT NULL,
    PRIMARY KEY (ID_PACIENTE, ID_CONVENIO),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO(ID_CONVENIO)
);